// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// edit_dist_matrix
IntegerMatrix edit_dist_matrix(const std::vector<std::string>& query, const std::vector<std::string>& target);
RcppExport SEXP _WavefrontAlignR_edit_dist_matrix(SEXP querySEXP, SEXP targetSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const std::vector<std::string>& >::type query(querySEXP);
    Rcpp::traits::input_parameter< const std::vector<std::string>& >::type target(targetSEXP);
    rcpp_result_gen = Rcpp::wrap(edit_dist_matrix(query, target));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_WavefrontAlignR_edit_dist_matrix", (DL_FUNC) &_WavefrontAlignR_edit_dist_matrix, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_WavefrontAlignR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
